name: Latest DEVto Blog Posts
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  devto-blog-posts:
    name: Update README with latest DEV.to Blog Posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "DEVTO-BLOG-LIST"
          feed_list: "https://dev.to/feed/nathanielchi"
